---
# tasks file for pve_clone
#
#  ████████╗ █████╗ ███████╗██╗  ██╗
#  ╚══██╔══╝██╔══██╗██╔════╝██║ ██╔╝
#     ██║   ███████║███████╗█████╔╝
#     ██║   ██╔══██║╚════██║██╔═██╗
#     ██║   ██║  ██║███████║██║  ██╗
#     ╚═╝   ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝
#

# -----------------------------------------------------------------------------
# Management of Qemu(KVM) Virtual Machines in a Proxmox VE cluster
# -----------------------------------------------------------------------------
- name: (pve_clone) | pve_clone_vm | Clone Proxmox template
  community.general.proxmox_kvm:
    api_host: "{{ pve_host }}"
    api_port: "{{ pve_port | default(8006) }}"
    api_token_id: "{{ pve_tokenid.split('!')[1] }}"
    api_token_secret: "{{ pve_token_secret }}"
    api_user: "{{ pve_tokenid.split('!')[0] }}"
    clone: arbitrary_name
    full: "{{ pve_full_copy }}"
    node: "{{ pve_node }}"
    pool: "{{ pve_pool | default(omit) }}"
    timeout: "{{ pve_timeout }}"
    vmid: "{{ pve_templateid }}"
    format: "{{ item.format | default(omit) }}"
    name: "{{ item.name }}"
    newid: "{{ item.newid | default(omit) }}"
    storage: "{{ item.storage | default(omit) }}"
    validate_certs: "{{ pve_validate_certs | default(false) }}"
  with_items:
    - "{{ new_vm }}"
